//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18051
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.18051 版自动生成。
// 
#pragma warning disable 1591

namespace MISClient.Service_SystemManagement {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service_SystemManagementSoap", Namespace="http://tempuri.org/")]
    public partial class Service_SystemManagement : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback Create_UserOperationCompleted;
        
        private System.Threading.SendOrPostCallback Find_UserAccountOperationCompleted;
        
        private System.Threading.SendOrPostCallback Select_UserAllOperationCompleted;
        
        private System.Threading.SendOrPostCallback Select_UserOperationCompleted;
        
        private System.Threading.SendOrPostCallback Delete_UserOperationCompleted;
        
        private System.Threading.SendOrPostCallback Update_UserOperationCompleted;
        
        private System.Threading.SendOrPostCallback checkPasswordOperationCompleted;
        
        private System.Threading.SendOrPostCallback Select_User_ByAcountOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service_SystemManagement() {
            this.Url = global::MISClient.Properties.Settings.Default.MISClient_Service_SystemManagement_Service_SystemManagement;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event Create_UserCompletedEventHandler Create_UserCompleted;
        
        /// <remarks/>
        public event Find_UserAccountCompletedEventHandler Find_UserAccountCompleted;
        
        /// <remarks/>
        public event Select_UserAllCompletedEventHandler Select_UserAllCompleted;
        
        /// <remarks/>
        public event Select_UserCompletedEventHandler Select_UserCompleted;
        
        /// <remarks/>
        public event Delete_UserCompletedEventHandler Delete_UserCompleted;
        
        /// <remarks/>
        public event Update_UserCompletedEventHandler Update_UserCompleted;
        
        /// <remarks/>
        public event checkPasswordCompletedEventHandler checkPasswordCompleted;
        
        /// <remarks/>
        public event Select_User_ByAcountCompletedEventHandler Select_User_ByAcountCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Create_User", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int Create_User(TabUsers user) {
            object[] results = this.Invoke("Create_User", new object[] {
                        user});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void Create_UserAsync(TabUsers user) {
            this.Create_UserAsync(user, null);
        }
        
        /// <remarks/>
        public void Create_UserAsync(TabUsers user, object userState) {
            if ((this.Create_UserOperationCompleted == null)) {
                this.Create_UserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreate_UserOperationCompleted);
            }
            this.InvokeAsync("Create_User", new object[] {
                        user}, this.Create_UserOperationCompleted, userState);
        }
        
        private void OnCreate_UserOperationCompleted(object arg) {
            if ((this.Create_UserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Create_UserCompleted(this, new Create_UserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Find_UserAccount", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int Find_UserAccount(string account) {
            object[] results = this.Invoke("Find_UserAccount", new object[] {
                        account});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void Find_UserAccountAsync(string account) {
            this.Find_UserAccountAsync(account, null);
        }
        
        /// <remarks/>
        public void Find_UserAccountAsync(string account, object userState) {
            if ((this.Find_UserAccountOperationCompleted == null)) {
                this.Find_UserAccountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFind_UserAccountOperationCompleted);
            }
            this.InvokeAsync("Find_UserAccount", new object[] {
                        account}, this.Find_UserAccountOperationCompleted, userState);
        }
        
        private void OnFind_UserAccountOperationCompleted(object arg) {
            if ((this.Find_UserAccountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Find_UserAccountCompleted(this, new Find_UserAccountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Select_UserAll", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TabUsers[] Select_UserAll() {
            object[] results = this.Invoke("Select_UserAll", new object[0]);
            return ((TabUsers[])(results[0]));
        }
        
        /// <remarks/>
        public void Select_UserAllAsync() {
            this.Select_UserAllAsync(null);
        }
        
        /// <remarks/>
        public void Select_UserAllAsync(object userState) {
            if ((this.Select_UserAllOperationCompleted == null)) {
                this.Select_UserAllOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelect_UserAllOperationCompleted);
            }
            this.InvokeAsync("Select_UserAll", new object[0], this.Select_UserAllOperationCompleted, userState);
        }
        
        private void OnSelect_UserAllOperationCompleted(object arg) {
            if ((this.Select_UserAllCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Select_UserAllCompleted(this, new Select_UserAllCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Select_User", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TabUsers Select_User(int userID) {
            object[] results = this.Invoke("Select_User", new object[] {
                        userID});
            return ((TabUsers)(results[0]));
        }
        
        /// <remarks/>
        public void Select_UserAsync(int userID) {
            this.Select_UserAsync(userID, null);
        }
        
        /// <remarks/>
        public void Select_UserAsync(int userID, object userState) {
            if ((this.Select_UserOperationCompleted == null)) {
                this.Select_UserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelect_UserOperationCompleted);
            }
            this.InvokeAsync("Select_User", new object[] {
                        userID}, this.Select_UserOperationCompleted, userState);
        }
        
        private void OnSelect_UserOperationCompleted(object arg) {
            if ((this.Select_UserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Select_UserCompleted(this, new Select_UserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Delete_User", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int Delete_User(TabUsers user) {
            object[] results = this.Invoke("Delete_User", new object[] {
                        user});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void Delete_UserAsync(TabUsers user) {
            this.Delete_UserAsync(user, null);
        }
        
        /// <remarks/>
        public void Delete_UserAsync(TabUsers user, object userState) {
            if ((this.Delete_UserOperationCompleted == null)) {
                this.Delete_UserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDelete_UserOperationCompleted);
            }
            this.InvokeAsync("Delete_User", new object[] {
                        user}, this.Delete_UserOperationCompleted, userState);
        }
        
        private void OnDelete_UserOperationCompleted(object arg) {
            if ((this.Delete_UserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Delete_UserCompleted(this, new Delete_UserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Update_User", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int Update_User(TabUsers user) {
            object[] results = this.Invoke("Update_User", new object[] {
                        user});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void Update_UserAsync(TabUsers user) {
            this.Update_UserAsync(user, null);
        }
        
        /// <remarks/>
        public void Update_UserAsync(TabUsers user, object userState) {
            if ((this.Update_UserOperationCompleted == null)) {
                this.Update_UserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdate_UserOperationCompleted);
            }
            this.InvokeAsync("Update_User", new object[] {
                        user}, this.Update_UserOperationCompleted, userState);
        }
        
        private void OnUpdate_UserOperationCompleted(object arg) {
            if ((this.Update_UserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Update_UserCompleted(this, new Update_UserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/checkPassword", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int checkPassword(string username, string password) {
            object[] results = this.Invoke("checkPassword", new object[] {
                        username,
                        password});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void checkPasswordAsync(string username, string password) {
            this.checkPasswordAsync(username, password, null);
        }
        
        /// <remarks/>
        public void checkPasswordAsync(string username, string password, object userState) {
            if ((this.checkPasswordOperationCompleted == null)) {
                this.checkPasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OncheckPasswordOperationCompleted);
            }
            this.InvokeAsync("checkPassword", new object[] {
                        username,
                        password}, this.checkPasswordOperationCompleted, userState);
        }
        
        private void OncheckPasswordOperationCompleted(object arg) {
            if ((this.checkPasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.checkPasswordCompleted(this, new checkPasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Select_User_ByAcount", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TabUsers[] Select_User_ByAcount(string account) {
            object[] results = this.Invoke("Select_User_ByAcount", new object[] {
                        account});
            return ((TabUsers[])(results[0]));
        }
        
        /// <remarks/>
        public void Select_User_ByAcountAsync(string account) {
            this.Select_User_ByAcountAsync(account, null);
        }
        
        /// <remarks/>
        public void Select_User_ByAcountAsync(string account, object userState) {
            if ((this.Select_User_ByAcountOperationCompleted == null)) {
                this.Select_User_ByAcountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelect_User_ByAcountOperationCompleted);
            }
            this.InvokeAsync("Select_User_ByAcount", new object[] {
                        account}, this.Select_User_ByAcountOperationCompleted, userState);
        }
        
        private void OnSelect_User_ByAcountOperationCompleted(object arg) {
            if ((this.Select_User_ByAcountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Select_User_ByAcountCompleted(this, new Select_User_ByAcountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TabUsers {
        
        private int uIDField;
        
        private string uAccountField;
        
        private string uPasswordField;
        
        private string uNameField;
        
        private string uDepartField;
        
        private string uPrivilegeField;
        
        /// <remarks/>
        public int UID {
            get {
                return this.uIDField;
            }
            set {
                this.uIDField = value;
            }
        }
        
        /// <remarks/>
        public string UAccount {
            get {
                return this.uAccountField;
            }
            set {
                this.uAccountField = value;
            }
        }
        
        /// <remarks/>
        public string UPassword {
            get {
                return this.uPasswordField;
            }
            set {
                this.uPasswordField = value;
            }
        }
        
        /// <remarks/>
        public string UName {
            get {
                return this.uNameField;
            }
            set {
                this.uNameField = value;
            }
        }
        
        /// <remarks/>
        public string UDepart {
            get {
                return this.uDepartField;
            }
            set {
                this.uDepartField = value;
            }
        }
        
        /// <remarks/>
        public string UPrivilege {
            get {
                return this.uPrivilegeField;
            }
            set {
                this.uPrivilegeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void Create_UserCompletedEventHandler(object sender, Create_UserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Create_UserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Create_UserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void Find_UserAccountCompletedEventHandler(object sender, Find_UserAccountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Find_UserAccountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Find_UserAccountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void Select_UserAllCompletedEventHandler(object sender, Select_UserAllCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Select_UserAllCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Select_UserAllCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TabUsers[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TabUsers[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void Select_UserCompletedEventHandler(object sender, Select_UserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Select_UserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Select_UserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TabUsers Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TabUsers)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void Delete_UserCompletedEventHandler(object sender, Delete_UserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Delete_UserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Delete_UserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void Update_UserCompletedEventHandler(object sender, Update_UserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Update_UserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Update_UserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void checkPasswordCompletedEventHandler(object sender, checkPasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class checkPasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal checkPasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void Select_User_ByAcountCompletedEventHandler(object sender, Select_User_ByAcountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Select_User_ByAcountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Select_User_ByAcountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TabUsers[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TabUsers[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591