//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3603
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeGeneratorLib.Resx {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeGeneratorLib.Resx.resource", typeof(resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 using System;
        ///using System.Collections;
        ///using System.Collections.Generic;
        ///using System.Data;
        ///using System.Data.SqlClient;
        ///using IBatisNet.Common;
        ///using IBatisNet.Common.Pagination;
        ///using IBatisNet.DataMapper;
        ///using IBatisNet.DataMapper.Exceptions;
        ///using IBatisNet.DataMapper.MappedStatements;
        ///using IBatisNet.DataMapper.Scope;
        ///
        ///${ComponentNameSpace}
        ///
        ///namespace ${DaoNameSpace}
        ///{
        ///    public abstract class BaseSqlMapDao
        ///    {
        ///        /// &lt;summary&gt;
        ///        /// ISqlMapper实例
        ///        /// 从Windsor [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string BaseSqlMap {
            get {
                return ResourceManager.GetString("BaseSqlMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;configuration&gt;
        ///  &lt;components&gt;
        ///    ${LogicComponent}
        ///  &lt;/components&gt;
        ///&lt;/configuration&gt; 的本地化字符串。
        /// </summary>
        internal static string CommonLogicsConfig {
            get {
                return ResourceManager.GetString("CommonLogicsConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;Project DefaultTargets=&quot;Build&quot; xmlns=&quot;http://schemas.microsoft.com/developer/msbuild/2003&quot;&gt;
        ///  &lt;PropertyGroup&gt;
        ///    &lt;Configuration Condition=&quot; &apos;$(Configuration)&apos; == &apos;&apos; &quot;&gt;Debug&lt;/Configuration&gt;
        ///    &lt;Platform Condition=&quot; &apos;$(Platform)&apos; == &apos;&apos; &quot;&gt;AnyCPU&lt;/Platform&gt;
        ///    &lt;ProductVersion&gt;8.0.50727&lt;/ProductVersion&gt;
        ///    &lt;SchemaVersion&gt;2.0&lt;/SchemaVersion&gt;
        ///    &lt;ProjectGuid&gt;{${Guid}}&lt;/ProjectGuid&gt;
        ///    &lt;OutputType&gt;Library&lt;/OutputType&gt;
        ///    &lt;AppDesignerFolder&gt;Properties&lt;/AppDesignerFolder&gt;
        ///    &lt;RootNamespace&gt;${NameSpa [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ComponentProject {
            get {
                return ResourceManager.GetString("ComponentProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using System.Web;
        ///using Castle.Windsor;
        ///
        ///namespace ${NameSpace}
        ///{
        ///    public class ContainerAccessorUtil
        ///    {
        ///        private ContainerAccessorUtil()
        ///        {
        ///        }
        ///
        ///        /// &lt;summary&gt;
        ///        /// Obtain the Cuyahoga container.
        ///        /// &lt;/summary&gt;
        ///        /// &lt;returns&gt;&lt;/returns&gt;
        ///        public static IWindsorContainer GetContainer()
        ///        {
        ///            IContainerAccessor containerAccessor = HttpContext.Curre [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ContainerAccessorUtil {
            get {
                return ResourceManager.GetString("ContainerAccessorUtil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string EntityBuild {
            get {
                return ResourceManager.GetString("EntityBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using System;
        ///using System.Collections.Generic;
        ///
        ///namespace ${NameSpace}
        ///{
        ///    [Serializable]
        ///	public class ${ClassName}
        ///	{
        ///		public ${ClassName}()
        ///		{
        ///			${Constructor}
        ///		}
        ///
        ///		${Fields}
        ///		
        ///		${EqualsHashCode}		
        ///	}
        ///} 的本地化字符串。
        /// </summary>
        internal static string EntityClass {
            get {
                return ResourceManager.GetString("EntityClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;Project DefaultTargets=&quot;Build&quot; xmlns=&quot;http://schemas.microsoft.com/developer/msbuild/2003&quot;&gt;
        ///	&lt;PropertyGroup&gt;
        ///		&lt;Configuration Condition=&quot; &apos;$(Configuration)&apos; == &apos;&apos; &quot;&gt;Debug&lt;/Configuration&gt;
        ///		&lt;Platform Condition=&quot; &apos;$(Platform)&apos; == &apos;&apos; &quot;&gt;AnyCPU&lt;/Platform&gt;
        ///		&lt;ProductVersion&gt;8.0.50727&lt;/ProductVersion&gt;
        ///		&lt;SchemaVersion&gt;2.0&lt;/SchemaVersion&gt;
        ///		&lt;ProjectGuid&gt;{${Guid}}&lt;/ProjectGuid&gt;
        ///		&lt;OutputType&gt;Library&lt;/OutputType&gt;
        ///		&lt;AppDesignerFolder&gt;Properties&lt;/AppDesignerFolder&gt;
        ///		&lt;RootNamespace&gt;${NameSpace}&lt;/RootNamespac [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string EntityProject {
            get {
                return ResourceManager.GetString("EntityProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;!--============================================================================
        /////	CAUTION: This file is generated by IBatisNetGen.BatisMap.cst at 2009-4-14 11:30:53
        /////				Any manual editing will be lost in re-generation.
        /////===========================================================================--&gt;
        ///&lt;sqlMap namespace=&quot;${ClassName}&quot;
        ///	xmlns=&quot;http://ibatis.apache.org/mapping&quot;
        ///	xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///
        ///  &lt;alias&gt;
        ///    &lt;typeAlias a [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string IBatisMapFile {
            get {
                return ResourceManager.GetString("IBatisMapFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using System;
        ///using System.Collections;
        ///using System.Collections.Generic;
        ///
        ///namespace ${LogicNameSpace}.Interface
        ///{
        ///    public interface ICommonLogic&lt;T, IdT&gt;
        ///    {
        ///        /// &lt;sammury&gt;
        ///        /// 创建对象
        ///        /// &lt;/sammury&gt;
        ///        /// &lt;param name=&quot;entity&quot;&gt;&lt;/param&gt;
        ///        /// &lt;returns&gt;&lt;/returns&gt;
        ///        void Create(T entity);
        ///
        ///        /// &lt;sammury&gt;
        ///        /// 更新对象
        ///        /// &lt;/sammury&gt;
        ///        /// &lt;param name=&quot;entity&quot;&gt;&lt;/param&gt;
        ///        /// &lt;returns&gt;&lt;/returns&gt;
        ///        int Update(T enti [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ICommonLogic {
            get {
                return ResourceManager.GetString("ICommonLogic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using System;
        ///using System.Collections.Generic;
        ///${EntityNameSpace}
        ///
        ///namespace ${LogicNameSpace}.Interface
        ///{
        ///    public interface I${ClassName}Logic : ICommonLogic&lt;${ClassName}, ${KeyType}&gt;
        ///    {
        ///    }
        ///} 的本地化字符串。
        /// </summary>
        internal static string IXXLogic {
            get {
                return ResourceManager.GetString("IXXLogic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;Project DefaultTargets=&quot;Build&quot; xmlns=&quot;http://schemas.microsoft.com/developer/msbuild/2003&quot;&gt;
        ///  &lt;PropertyGroup&gt;
        ///    &lt;Configuration Condition=&quot; &apos;$(Configuration)&apos; == &apos;&apos; &quot;&gt;Debug&lt;/Configuration&gt;
        ///    &lt;Platform Condition=&quot; &apos;$(Platform)&apos; == &apos;&apos; &quot;&gt;AnyCPU&lt;/Platform&gt;
        ///    &lt;ProductVersion&gt;8.0.50727&lt;/ProductVersion&gt;
        ///    &lt;SchemaVersion&gt;2.0&lt;/SchemaVersion&gt;
        ///    &lt;ProjectGuid&gt;{${Guid}}&lt;/ProjectGuid&gt;
        ///    &lt;OutputType&gt;Library&lt;/OutputType&gt;
        ///    &lt;AppDesignerFolder&gt;Properties&lt;/AppDesignerFolder&gt;
        ///    &lt;RootNamespace&gt;${NameSpa [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string LogicProject {
            get {
                return ResourceManager.GetString("LogicProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using System.Reflection;
        ///using System.Runtime.CompilerServices;
        ///using System.Runtime.InteropServices;
        ///
        ///// 有关程序集的常规信息通过下列属性集
        ///// 控制。更改这些属性值可修改
        ///// 与程序集关联的信息。
        ///[assembly: AssemblyTitle(&quot;${Assembly}&quot;)]
        ///[assembly: AssemblyDescription(&quot;&quot;)]
        ///[assembly: AssemblyConfiguration(&quot;&quot;)]
        ///[assembly: AssemblyCompany(&quot;武汉聚网科技有限公司&quot;)]
        ///[assembly: AssemblyProduct(&quot;${Assembly}&quot;)]
        ///[assembly: AssemblyCopyright(&quot;版权所有 武汉聚网科技有限公司 (C) 2009&quot;)]
        ///[assembly: AssemblyTrademark(&quot;&quot;)]
        ///[assembly: AssemblyCulture(&quot;&quot;)]
        ///
        ///// 将 ComVisible  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Properties {
            get {
                return ResourceManager.GetString("Properties", resourceCulture);
            }
        }
        
        internal static byte[] SharedLib {
            get {
                object obj = ResourceManager.GetObject("SharedLib", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;sqlMapConfig
        ///  xmlns=&quot;http://ibatis.apache.org/dataMapper&quot;
        ///  xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///
        ///
        ///  &lt;settings&gt;
        ///    &lt;setting useStatementNamespaces=&quot;true&quot;/&gt;
        ///  &lt;/settings&gt;
        ///
        ///  &lt;providers resource=&quot;Config/providers.config&quot;/&gt;
        ///
        ///  &lt;!-- Database connection information --&gt;
        ///  &lt;database&gt;
        ///    &lt;provider name=&quot;sqlServer1.1&quot;/&gt;
        ///    &lt;dataSource name=&quot;GWEE&quot; connectionString=&quot;${ConnectionString}&quot; /&gt;
        ///  &lt;/database&gt;
        ///  &lt;sqlMaps&gt;
        ///    ${SqlMap}
        ///  &lt;/sqlMa [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string SqlMapConfig {
            get {
                return ResourceManager.GetString("SqlMapConfig", resourceCulture);
            }
        }
        
        internal static byte[] Web {
            get {
                object obj = ResourceManager.GetObject("Web", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 using System;
        ///using System.Collections;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///
        ///
        ///${EntityNameSpace}
        ///
        ///namespace ${LogicNameSpace}
        ///{
        ///    public class ${ClassName}Logic : : AbstractCommonLogic&lt;${ClassName}, ${KeyType}&gt;
        ///    {
        ///
        ///        /// &lt;sammury&gt;
        ///        /// 创建对象
        ///        /// &lt;/sammury&gt;
        ///        /// &lt;param name=&quot;entity&quot;&gt;&lt;/param&gt;
        ///        /// &lt;returns&gt;&lt;/returns&gt;
        ///        public int Create(${ClassName} entity)
        ///        {
        ///            return CreateObject(entity);
        ///        }
        ///
        ///        [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string XXLogic {
            get {
                return ResourceManager.GetString("XXLogic", resourceCulture);
            }
        }
    }
}
