//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18051
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.18051 版自动生成。
// 
#pragma warning disable 1591

namespace MISClient.Service_NewProject {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service_NewProjectSoap", Namespace="http://tempuri.org/")]
    public partial class Service_NewProject : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback add_ProjectInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback add_SubProjectInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback select_ProjectInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback select_SubProjectInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback delete_ProjectInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback delete_subProjectInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback update_ProjectInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback update_SubProjectInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback update_ExInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback update_PlanOperationCompleted;
        
        private System.Threading.SendOrPostCallback add_ImageOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service_NewProject() {
            this.Url = global::MISClient.Properties.Settings.Default.MISClient_Service_NewProject_Service_NewProject;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event add_ProjectInfoCompletedEventHandler add_ProjectInfoCompleted;
        
        /// <remarks/>
        public event add_SubProjectInfoCompletedEventHandler add_SubProjectInfoCompleted;
        
        /// <remarks/>
        public event select_ProjectInfoCompletedEventHandler select_ProjectInfoCompleted;
        
        /// <remarks/>
        public event select_SubProjectInfoCompletedEventHandler select_SubProjectInfoCompleted;
        
        /// <remarks/>
        public event delete_ProjectInfoCompletedEventHandler delete_ProjectInfoCompleted;
        
        /// <remarks/>
        public event delete_subProjectInfoCompletedEventHandler delete_subProjectInfoCompleted;
        
        /// <remarks/>
        public event update_ProjectInfoCompletedEventHandler update_ProjectInfoCompleted;
        
        /// <remarks/>
        public event update_SubProjectInfoCompletedEventHandler update_SubProjectInfoCompleted;
        
        /// <remarks/>
        public event update_ExInfoCompletedEventHandler update_ExInfoCompleted;
        
        /// <remarks/>
        public event update_PlanCompletedEventHandler update_PlanCompleted;
        
        /// <remarks/>
        public event add_ImageCompletedEventHandler add_ImageCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/add_ProjectInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int add_ProjectInfo(TabProjectInfo projectInfo) {
            object[] results = this.Invoke("add_ProjectInfo", new object[] {
                        projectInfo});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void add_ProjectInfoAsync(TabProjectInfo projectInfo) {
            this.add_ProjectInfoAsync(projectInfo, null);
        }
        
        /// <remarks/>
        public void add_ProjectInfoAsync(TabProjectInfo projectInfo, object userState) {
            if ((this.add_ProjectInfoOperationCompleted == null)) {
                this.add_ProjectInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.Onadd_ProjectInfoOperationCompleted);
            }
            this.InvokeAsync("add_ProjectInfo", new object[] {
                        projectInfo}, this.add_ProjectInfoOperationCompleted, userState);
        }
        
        private void Onadd_ProjectInfoOperationCompleted(object arg) {
            if ((this.add_ProjectInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.add_ProjectInfoCompleted(this, new add_ProjectInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/add_SubProjectInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int add_SubProjectInfo(TabSubProjectInfo subProjectInfo) {
            object[] results = this.Invoke("add_SubProjectInfo", new object[] {
                        subProjectInfo});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void add_SubProjectInfoAsync(TabSubProjectInfo subProjectInfo) {
            this.add_SubProjectInfoAsync(subProjectInfo, null);
        }
        
        /// <remarks/>
        public void add_SubProjectInfoAsync(TabSubProjectInfo subProjectInfo, object userState) {
            if ((this.add_SubProjectInfoOperationCompleted == null)) {
                this.add_SubProjectInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.Onadd_SubProjectInfoOperationCompleted);
            }
            this.InvokeAsync("add_SubProjectInfo", new object[] {
                        subProjectInfo}, this.add_SubProjectInfoOperationCompleted, userState);
        }
        
        private void Onadd_SubProjectInfoOperationCompleted(object arg) {
            if ((this.add_SubProjectInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.add_SubProjectInfoCompleted(this, new add_SubProjectInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/select_ProjectInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TabProjectInfo[] select_ProjectInfo() {
            object[] results = this.Invoke("select_ProjectInfo", new object[0]);
            return ((TabProjectInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void select_ProjectInfoAsync() {
            this.select_ProjectInfoAsync(null);
        }
        
        /// <remarks/>
        public void select_ProjectInfoAsync(object userState) {
            if ((this.select_ProjectInfoOperationCompleted == null)) {
                this.select_ProjectInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.Onselect_ProjectInfoOperationCompleted);
            }
            this.InvokeAsync("select_ProjectInfo", new object[0], this.select_ProjectInfoOperationCompleted, userState);
        }
        
        private void Onselect_ProjectInfoOperationCompleted(object arg) {
            if ((this.select_ProjectInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.select_ProjectInfoCompleted(this, new select_ProjectInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/select_SubProjectInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TabSubProjectInfo[] select_SubProjectInfo() {
            object[] results = this.Invoke("select_SubProjectInfo", new object[0]);
            return ((TabSubProjectInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void select_SubProjectInfoAsync() {
            this.select_SubProjectInfoAsync(null);
        }
        
        /// <remarks/>
        public void select_SubProjectInfoAsync(object userState) {
            if ((this.select_SubProjectInfoOperationCompleted == null)) {
                this.select_SubProjectInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.Onselect_SubProjectInfoOperationCompleted);
            }
            this.InvokeAsync("select_SubProjectInfo", new object[0], this.select_SubProjectInfoOperationCompleted, userState);
        }
        
        private void Onselect_SubProjectInfoOperationCompleted(object arg) {
            if ((this.select_SubProjectInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.select_SubProjectInfoCompleted(this, new select_SubProjectInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/delete_ProjectInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int delete_ProjectInfo(int id) {
            object[] results = this.Invoke("delete_ProjectInfo", new object[] {
                        id});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void delete_ProjectInfoAsync(int id) {
            this.delete_ProjectInfoAsync(id, null);
        }
        
        /// <remarks/>
        public void delete_ProjectInfoAsync(int id, object userState) {
            if ((this.delete_ProjectInfoOperationCompleted == null)) {
                this.delete_ProjectInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.Ondelete_ProjectInfoOperationCompleted);
            }
            this.InvokeAsync("delete_ProjectInfo", new object[] {
                        id}, this.delete_ProjectInfoOperationCompleted, userState);
        }
        
        private void Ondelete_ProjectInfoOperationCompleted(object arg) {
            if ((this.delete_ProjectInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.delete_ProjectInfoCompleted(this, new delete_ProjectInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/delete_subProjectInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int delete_subProjectInfo(int id) {
            object[] results = this.Invoke("delete_subProjectInfo", new object[] {
                        id});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void delete_subProjectInfoAsync(int id) {
            this.delete_subProjectInfoAsync(id, null);
        }
        
        /// <remarks/>
        public void delete_subProjectInfoAsync(int id, object userState) {
            if ((this.delete_subProjectInfoOperationCompleted == null)) {
                this.delete_subProjectInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.Ondelete_subProjectInfoOperationCompleted);
            }
            this.InvokeAsync("delete_subProjectInfo", new object[] {
                        id}, this.delete_subProjectInfoOperationCompleted, userState);
        }
        
        private void Ondelete_subProjectInfoOperationCompleted(object arg) {
            if ((this.delete_subProjectInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.delete_subProjectInfoCompleted(this, new delete_subProjectInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/update_ProjectInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int update_ProjectInfo(TabProjectInfo projectInfo) {
            object[] results = this.Invoke("update_ProjectInfo", new object[] {
                        projectInfo});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void update_ProjectInfoAsync(TabProjectInfo projectInfo) {
            this.update_ProjectInfoAsync(projectInfo, null);
        }
        
        /// <remarks/>
        public void update_ProjectInfoAsync(TabProjectInfo projectInfo, object userState) {
            if ((this.update_ProjectInfoOperationCompleted == null)) {
                this.update_ProjectInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.Onupdate_ProjectInfoOperationCompleted);
            }
            this.InvokeAsync("update_ProjectInfo", new object[] {
                        projectInfo}, this.update_ProjectInfoOperationCompleted, userState);
        }
        
        private void Onupdate_ProjectInfoOperationCompleted(object arg) {
            if ((this.update_ProjectInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.update_ProjectInfoCompleted(this, new update_ProjectInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/update_SubProjectInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int update_SubProjectInfo(TabSubProjectInfo subProjectInfo) {
            object[] results = this.Invoke("update_SubProjectInfo", new object[] {
                        subProjectInfo});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void update_SubProjectInfoAsync(TabSubProjectInfo subProjectInfo) {
            this.update_SubProjectInfoAsync(subProjectInfo, null);
        }
        
        /// <remarks/>
        public void update_SubProjectInfoAsync(TabSubProjectInfo subProjectInfo, object userState) {
            if ((this.update_SubProjectInfoOperationCompleted == null)) {
                this.update_SubProjectInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.Onupdate_SubProjectInfoOperationCompleted);
            }
            this.InvokeAsync("update_SubProjectInfo", new object[] {
                        subProjectInfo}, this.update_SubProjectInfoOperationCompleted, userState);
        }
        
        private void Onupdate_SubProjectInfoOperationCompleted(object arg) {
            if ((this.update_SubProjectInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.update_SubProjectInfoCompleted(this, new update_SubProjectInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/update_ExInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int update_ExInfo(TabProjectInfo projectInfo) {
            object[] results = this.Invoke("update_ExInfo", new object[] {
                        projectInfo});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void update_ExInfoAsync(TabProjectInfo projectInfo) {
            this.update_ExInfoAsync(projectInfo, null);
        }
        
        /// <remarks/>
        public void update_ExInfoAsync(TabProjectInfo projectInfo, object userState) {
            if ((this.update_ExInfoOperationCompleted == null)) {
                this.update_ExInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.Onupdate_ExInfoOperationCompleted);
            }
            this.InvokeAsync("update_ExInfo", new object[] {
                        projectInfo}, this.update_ExInfoOperationCompleted, userState);
        }
        
        private void Onupdate_ExInfoOperationCompleted(object arg) {
            if ((this.update_ExInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.update_ExInfoCompleted(this, new update_ExInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/update_Plan", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int update_Plan(TabProjectInfo projectInfo) {
            object[] results = this.Invoke("update_Plan", new object[] {
                        projectInfo});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void update_PlanAsync(TabProjectInfo projectInfo) {
            this.update_PlanAsync(projectInfo, null);
        }
        
        /// <remarks/>
        public void update_PlanAsync(TabProjectInfo projectInfo, object userState) {
            if ((this.update_PlanOperationCompleted == null)) {
                this.update_PlanOperationCompleted = new System.Threading.SendOrPostCallback(this.Onupdate_PlanOperationCompleted);
            }
            this.InvokeAsync("update_Plan", new object[] {
                        projectInfo}, this.update_PlanOperationCompleted, userState);
        }
        
        private void Onupdate_PlanOperationCompleted(object arg) {
            if ((this.update_PlanCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.update_PlanCompleted(this, new update_PlanCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/add_Image", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int add_Image(TabImage image) {
            object[] results = this.Invoke("add_Image", new object[] {
                        image});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void add_ImageAsync(TabImage image) {
            this.add_ImageAsync(image, null);
        }
        
        /// <remarks/>
        public void add_ImageAsync(TabImage image, object userState) {
            if ((this.add_ImageOperationCompleted == null)) {
                this.add_ImageOperationCompleted = new System.Threading.SendOrPostCallback(this.Onadd_ImageOperationCompleted);
            }
            this.InvokeAsync("add_Image", new object[] {
                        image}, this.add_ImageOperationCompleted, userState);
        }
        
        private void Onadd_ImageOperationCompleted(object arg) {
            if ((this.add_ImageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.add_ImageCompleted(this, new add_ImageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TabProjectInfo {
        
        private int pIDField;
        
        private string pNOField;
        
        private string pNameField;
        
        private string pConstructionField;
        
        private string pBuilderField;
        
        private string pStateField;
        
        private string pCustomerField;
        
        private string pCategoryField;
        
        private string pBusinessPlanField;
        
        private System.Nullable<System.DateTime> pDateTimeField;
        
        private System.Nullable<decimal> pContractAmountField;
        
        private System.Nullable<decimal> pAuditorsField;
        
        private System.Nullable<decimal> pAllocationField;
        
        private System.Nullable<decimal> pPlanField;
        
        private System.Nullable<decimal> pRatioField;
        
        private System.Nullable<System.DateTime> pDisclosureField;
        
        private System.Nullable<System.DateTime> pStartDateField;
        
        private System.Nullable<System.DateTime> pEndDateField;
        
        private string pDesignChangeField;
        
        private string pDataInField;
        
        private string pCompletionField;
        
        private string pManagerField;
        
        private string pTelField;
        
        private string pTeleComNOField;
        
        /// <remarks/>
        public int PID {
            get {
                return this.pIDField;
            }
            set {
                this.pIDField = value;
            }
        }
        
        /// <remarks/>
        public string PNO {
            get {
                return this.pNOField;
            }
            set {
                this.pNOField = value;
            }
        }
        
        /// <remarks/>
        public string PName {
            get {
                return this.pNameField;
            }
            set {
                this.pNameField = value;
            }
        }
        
        /// <remarks/>
        public string PConstruction {
            get {
                return this.pConstructionField;
            }
            set {
                this.pConstructionField = value;
            }
        }
        
        /// <remarks/>
        public string PBuilder {
            get {
                return this.pBuilderField;
            }
            set {
                this.pBuilderField = value;
            }
        }
        
        /// <remarks/>
        public string PState {
            get {
                return this.pStateField;
            }
            set {
                this.pStateField = value;
            }
        }
        
        /// <remarks/>
        public string PCustomer {
            get {
                return this.pCustomerField;
            }
            set {
                this.pCustomerField = value;
            }
        }
        
        /// <remarks/>
        public string PCategory {
            get {
                return this.pCategoryField;
            }
            set {
                this.pCategoryField = value;
            }
        }
        
        /// <remarks/>
        public string PBusinessPlan {
            get {
                return this.pBusinessPlanField;
            }
            set {
                this.pBusinessPlanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> PDateTime {
            get {
                return this.pDateTimeField;
            }
            set {
                this.pDateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> PContractAmount {
            get {
                return this.pContractAmountField;
            }
            set {
                this.pContractAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> PAuditors {
            get {
                return this.pAuditorsField;
            }
            set {
                this.pAuditorsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> PAllocation {
            get {
                return this.pAllocationField;
            }
            set {
                this.pAllocationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> PPlan {
            get {
                return this.pPlanField;
            }
            set {
                this.pPlanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> PRatio {
            get {
                return this.pRatioField;
            }
            set {
                this.pRatioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> PDisclosure {
            get {
                return this.pDisclosureField;
            }
            set {
                this.pDisclosureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> PStartDate {
            get {
                return this.pStartDateField;
            }
            set {
                this.pStartDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> PEndDate {
            get {
                return this.pEndDateField;
            }
            set {
                this.pEndDateField = value;
            }
        }
        
        /// <remarks/>
        public string PDesignChange {
            get {
                return this.pDesignChangeField;
            }
            set {
                this.pDesignChangeField = value;
            }
        }
        
        /// <remarks/>
        public string PDataIn {
            get {
                return this.pDataInField;
            }
            set {
                this.pDataInField = value;
            }
        }
        
        /// <remarks/>
        public string PCompletion {
            get {
                return this.pCompletionField;
            }
            set {
                this.pCompletionField = value;
            }
        }
        
        /// <remarks/>
        public string PManager {
            get {
                return this.pManagerField;
            }
            set {
                this.pManagerField = value;
            }
        }
        
        /// <remarks/>
        public string PTel {
            get {
                return this.pTelField;
            }
            set {
                this.pTelField = value;
            }
        }
        
        /// <remarks/>
        public string PTeleComNO {
            get {
                return this.pTeleComNOField;
            }
            set {
                this.pTeleComNOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TabImage {
        
        private System.Nullable<int> tIIDField;
        
        private System.Nullable<int> tIProjectIDField;
        
        private System.Nullable<int> tISubProjectIDField;
        
        private System.Nullable<int> tINOField;
        
        private byte[] tIImageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> TIID {
            get {
                return this.tIIDField;
            }
            set {
                this.tIIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> TIProjectID {
            get {
                return this.tIProjectIDField;
            }
            set {
                this.tIProjectIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> TISubProjectID {
            get {
                return this.tISubProjectIDField;
            }
            set {
                this.tISubProjectIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> TINO {
            get {
                return this.tINOField;
            }
            set {
                this.tINOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] TIImage {
            get {
                return this.tIImageField;
            }
            set {
                this.tIImageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TabSubProjectInfo {
        
        private int sPIDField;
        
        private int sPProjectIDField;
        
        private string sPNOField;
        
        private string sPNameField;
        
        private string sPStateField;
        
        private System.Nullable<System.DateTime> sPDateField;
        
        private System.Nullable<decimal> sPContractAmountField;
        
        private System.Nullable<decimal> sPAuditorsField;
        
        private System.Nullable<decimal> sPRatioField;
        
        private string sPManagerField;
        
        private string sPTelField;
        
        /// <remarks/>
        public int SPID {
            get {
                return this.sPIDField;
            }
            set {
                this.sPIDField = value;
            }
        }
        
        /// <remarks/>
        public int SPProjectID {
            get {
                return this.sPProjectIDField;
            }
            set {
                this.sPProjectIDField = value;
            }
        }
        
        /// <remarks/>
        public string SPNO {
            get {
                return this.sPNOField;
            }
            set {
                this.sPNOField = value;
            }
        }
        
        /// <remarks/>
        public string SPName {
            get {
                return this.sPNameField;
            }
            set {
                this.sPNameField = value;
            }
        }
        
        /// <remarks/>
        public string SPState {
            get {
                return this.sPStateField;
            }
            set {
                this.sPStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> SPDate {
            get {
                return this.sPDateField;
            }
            set {
                this.sPDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> SPContractAmount {
            get {
                return this.sPContractAmountField;
            }
            set {
                this.sPContractAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> SPAuditors {
            get {
                return this.sPAuditorsField;
            }
            set {
                this.sPAuditorsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> SPRatio {
            get {
                return this.sPRatioField;
            }
            set {
                this.sPRatioField = value;
            }
        }
        
        /// <remarks/>
        public string SPManager {
            get {
                return this.sPManagerField;
            }
            set {
                this.sPManagerField = value;
            }
        }
        
        /// <remarks/>
        public string SPTel {
            get {
                return this.sPTelField;
            }
            set {
                this.sPTelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void add_ProjectInfoCompletedEventHandler(object sender, add_ProjectInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class add_ProjectInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal add_ProjectInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void add_SubProjectInfoCompletedEventHandler(object sender, add_SubProjectInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class add_SubProjectInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal add_SubProjectInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void select_ProjectInfoCompletedEventHandler(object sender, select_ProjectInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class select_ProjectInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal select_ProjectInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TabProjectInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TabProjectInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void select_SubProjectInfoCompletedEventHandler(object sender, select_SubProjectInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class select_SubProjectInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal select_SubProjectInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TabSubProjectInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TabSubProjectInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void delete_ProjectInfoCompletedEventHandler(object sender, delete_ProjectInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class delete_ProjectInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal delete_ProjectInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void delete_subProjectInfoCompletedEventHandler(object sender, delete_subProjectInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class delete_subProjectInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal delete_subProjectInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void update_ProjectInfoCompletedEventHandler(object sender, update_ProjectInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class update_ProjectInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal update_ProjectInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void update_SubProjectInfoCompletedEventHandler(object sender, update_SubProjectInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class update_SubProjectInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal update_SubProjectInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void update_ExInfoCompletedEventHandler(object sender, update_ExInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class update_ExInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal update_ExInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void update_PlanCompletedEventHandler(object sender, update_PlanCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class update_PlanCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal update_PlanCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void add_ImageCompletedEventHandler(object sender, add_ImageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class add_ImageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal add_ImageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591